site_name: MkDocs PVT-thermal-performance-model
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - navigation.path
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language : en
  palette :
    - scheme: default
      toggle:
        icon : material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme : slate
      toggle:
        icon : material/toggle-switch
        name: Switch to light mode
      primary : teal
      accent : lime

extra:
  social:
    - icon : fontawesome/brands/github-alt
      link : https://github.com/valentindelachaux/PVT-thermal-performance-model
  
  markdown_extensions:
  - pymdownx.highlight:
    anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
    generic : true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji 
    emoji_generator: !!python/name:material.extensions.emoji.to_svg



nav:
  - "Home": index.md
  - "General": general.md
  - "Heat transfer": heat_transfer.md
  - "Model heat transfer": model_ht.md
  - "Model temperatures": model_temperatures.md
  - "Model transfers": model_transfers.md
  - "Model": model.md
  - "Model MPE": mpe_model.md
  - "Plot functions": plot_functions_here.md
  - "Proc": proc.md

plugins:
  - search
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      default_handler: python
      handlers:
        python:
          options:
            show_source: true


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js